//
// Created by JoakimKB on 17.11.2025.
//

#ifndef BALBOA_32U4_STUDENT_PROJECT_G2_BALBOA_SENSORS_H
#define BALBOA_32U4_STUDENT_PROJECT_G2_BALBOA_SENSORS_H

#endif //BALBOA_32U4_STUDENT_PROJECT_G2_BALBOA_SENSORS_H